// Autogenerated from "./BlackToAlpha.glsl"

/// <reference path="../../lib/pixi.d.ts"/>

interface Uniforms
{
}

export default class BlackToAlpha extends PIXI.AbstractFilter
{
  uniforms: Uniforms

  constructor(uniforms?: Uniforms)
  {
    super(null, sourceLines.join("\n"), uniforms);
  }
  public static getUniformTypes()
  {
    return(
    {
    });
   }
}

const sourceLines =
[
  "precision mediump float;",
  "",
  "varying vec2 vTextureCoord;",
  "uniform sampler2D uSampler;",
  "",
  "void main()",
  "{",
  "  vec4 color = texture2D(uSampler, vTextureCoord);",
  "  color.a = (color.r + color.g + color.b) / 3.0;",
  "",
  "  gl_FragColor = color;",
  "}",
]
