// Autogenerated from "./Occupation.glsl"

/// <reference path="../../lib/pixi.d.ts"/>

interface Uniforms
{
  baseColor: {type: "4fv"; value: number[];};
  gapSize: {type: "1f"; value: number;};
  lineColor: {type: "4fv"; value: number[];};
  offset: {type: "2fv"; value: number[];};
  zoom: {type: "1f"; value: number;};
}

interface PartialUniformValues
{
  baseColor?: number[];
  gapSize?: number;
  lineColor?: number[];
  offset?: number[];
  zoom?: number;
}

export default class Occupation extends PIXI.AbstractFilter
{
  public uniforms: Uniforms // needs to be public for PIXI, but shouldnt be accessed

  constructor(initialUniformValues?: PartialUniformValues)
  {
    const uniforms = Occupation.makeUniformsObject(initialUniformValues);
    super(null, sourceLines.join("\n"), uniforms);
  }
  private static makeUniformsObject(initialValues: PartialUniformValues = {}): Uniforms
  {
    return(
    {
      baseColor: {type: "4fv", value: initialValues.baseColor},
      gapSize: {type: "1f", value: initialValues.gapSize},
      lineColor: {type: "4fv", value: initialValues.lineColor},
      offset: {type: "2fv", value: initialValues.offset},
      zoom: {type: "1f", value: initialValues.zoom},
    });
  }
  public setUniformValues(values: PartialUniformValues)
  {
    for (let key in values)
    {
      this.uniforms[key].value = values[key];
    }
  }
}

const sourceLines =
[
  "precision mediump float;",
  "",
  "uniform vec4 baseColor;",
  "uniform vec4 lineColor;",
  "uniform float gapSize;",
  "uniform vec2 offset;",
  "uniform float zoom;",
  "",
  "void main( void )",
  "{",
  "  vec2 position = gl_FragCoord.xy + offset;",
  "  position.x += position.y;",
  "  float scaled = floor(position.x * 0.1 / zoom);",
  "  float res = mod(scaled, gapSize);",
  "  if(res > 0.0)",
  "  {",
  "    gl_FragColor = mix(gl_FragColor, baseColor, 0.5);",
  "  }",
  "  else",
  "  {",
  "    gl_FragColor = mix(gl_FragColor, lineColor, 0.5);",
  "  }",
  "}",
]
