export const galaxyMapUI =
{
  technology: "Technology",
  diplomacy: "Diplomacy",
  economy: "Economy",
  production: "Production",
  equip: "Equip",
  turnCounter: "Turn",
  income: "Income",
  endTurn: "End turn",
  mapMode: "Map mode",
  constructBuilding: "construct",
  upgradeBuilding: "upgrade",
  buildingCost: "Cost",
  buildingTypeName: "Name",
  attackTarget_action: "attack",
  attackTargetTooltip: "Attack {enemyName, possessiveName} {targetType}",
  coordinates: "x: {0}, y: {1}",
  terrainType: "Terrain: {0}",
  incomeAmount: "Income: {0}",

  topMenuButtonActionExplanation: "Left click to open. Right click to close",
  topMenuButtonTooltip_production: "Produce units and items",
  topMenuButtonTooltip_equip: "Equip & inspect units",
  topMenuButtonTooltip_economy: "",
  topMenuButtonTooltip_diplomacy: "Manage diplomacy & trade",
  topMenuButtonTooltip_technology: "Allocate research & view unlocks",
  topMenuButtonTooltip_load: "Load game",
  topMenuButtonTooltip_save: "Save game",
  topMenuButtonTooltip_options: "Configure options",
  topMenuButtonTooltip_openCondensedMenu: "Expand menu",
};
