export const options =
{
  options: "Options",
  language: "Language",
  debug: "Debug",
  logging: "Logging",
  ui: "UI",
  system: "System",
  fullLanguageSupport: "Full language support",
  partialLanguageSupport: "Partial language support",
  battleAnimationTiming: "Battle animation timing",
  beforeAbility: "Before ability (ms)",
  abilityEffectDuration: "Ability effect duration (*)",
  afterAbility: "After ability (ms)",
  unitEnter: "Unit enter (ms)",
  unitExit: "Unit exit (ms)",
  turnTransition: "Turn transition (ms)",
  debugMode: "Debug mode",
  aiVsPlayerBattleSimulationDepth: "AI vs. Player battle simulation depth",
  aiVsAiBattleSimulationDepth: "AI vs. AI battle simulation depth",
  aiLogging: "AI",
  graphicsLogging: "Graphics",
  savesLogging: "Saves",
  modulesLogging: "Modules",
  initLogging: "Init",
  alwaysExpandTopRightMenuOnLowResolution: "Always expand top right menu on low resolution",
  messageSettings: "Message settings",
  resetTutorials: "Reset tutorials",
  resetAllOptions: "Reset all options",
  areYouSureYouWantToResetAllOptions: "Are you sure you want to reset all options?",
  errorReportingMode: "Error reporting",
  errorReportingMode_ignore: "ignore",
  errorReportingModeDescription_ignore: "Silently ignore warnings",
  errorReportingMode_alert: "alert",
  errorReportingMode_alertOnce: "alert once",
  errorReportingModeDescription_alert: "Alert the user of an error occurring with a popup",
  errorReportingMode_panic: "panic",
  errorReportingModeDescription_panic: "Shut down the game and enter save recovery mode (Also possible from alert popup)",
};
