export const abilities =
{
  closeAttack_displayName: "Close Attack",
  closeAttack_description: "Close range attack that hits adjacent targets in the same row",
  beamAttack_displayName: "Beam Attack",
  beamAttack_description: "Attack units in a line",
  bombAttack_displayName: "Bomb Attack",
  bombAttack_description: "Ranged attack that hits all adjacent enemy units",
  boardingHook_displayName: "Boarding Hook",
  boardingHook_description: "0.8x damage but increases target capture chance",
  rangedAttack_displayName: "Ranged Attack",
  rangedAttack_description: "Standard ranged attack",
  snipeAttack_displayName: "Snipe: Attack",
  snipeAttack_description: "Deals damage and lowers target attack",
  snipeDefence_displayName: "Snipe: Defence",
  snipeDefence_description: "Deals damage and lowers target defence",
  snipeIntelligence_displayName: "Snipe: Intelligence",
  snipeIntelligence_description: "Deals damage and lowers target intelligence",
  snipeSpeed_displayName: "Snipe: Speed",
  snipeSpeed_description: "Deals damage and lowers target speed",
};
