// Autogenerated from "./Beam.glsl"

/// <reference path="../../../../lib/pixi.d.ts"/>

interface Uniforms
{
  aspectRatio: {type: "1f"; value: number;};
  beamColor: {type: "4fv"; value: number[];};
  beamYPosition: {type: "1f"; value: number;};
  bulgeIntensity: {type: "1f"; value: number;};
  bulgeSharpness: {type: "1f"; value: number;};
  bulgeSize: {type: "2fv"; value: number[];};
  bulgeXPosition: {type: "1f"; value: number;};
  lineIntensity: {type: "1f"; value: number;};
  lineXSharpness: {type: "1f"; value: number;};
  lineXSize: {type: "2fv"; value: number[];};
  lineYSharpness: {type: "1f"; value: number;};
  lineYSize: {type: "1f"; value: number;};
  noiseAmplitude: {type: "1f"; value: number;};
  seed: {type: "1f"; value: number;};
  time: {type: "1f"; value: number;};
}

interface PartialUniformValues
{
  aspectRatio?: number;
  beamColor?: number[];
  beamYPosition?: number;
  bulgeIntensity?: number;
  bulgeSharpness?: number;
  bulgeSize?: number[];
  bulgeXPosition?: number;
  lineIntensity?: number;
  lineXSharpness?: number;
  lineXSize?: number[];
  lineYSharpness?: number;
  lineYSize?: number;
  noiseAmplitude?: number;
  seed?: number;
  time?: number;
}

export default class Beam extends PIXI.Filter
{
  public uniforms: Uniforms // needs to be public for PIXI, but shouldnt be accessed

  constructor(initialUniformValues?: PartialUniformValues)
  {
    const uniforms = Beam.makeUniformsObject(initialUniformValues);
    super(null, sourceLines.join("\n"), uniforms);
  }
  private static makeUniformsObject(initialValues: PartialUniformValues = {}): Uniforms
  {
    return(
    {
      aspectRatio: {type: "1f", value: initialValues.aspectRatio},
      beamColor: {type: "4fv", value: initialValues.beamColor},
      beamYPosition: {type: "1f", value: initialValues.beamYPosition},
      bulgeIntensity: {type: "1f", value: initialValues.bulgeIntensity},
      bulgeSharpness: {type: "1f", value: initialValues.bulgeSharpness},
      bulgeSize: {type: "2fv", value: initialValues.bulgeSize},
      bulgeXPosition: {type: "1f", value: initialValues.bulgeXPosition},
      lineIntensity: {type: "1f", value: initialValues.lineIntensity},
      lineXSharpness: {type: "1f", value: initialValues.lineXSharpness},
      lineXSize: {type: "2fv", value: initialValues.lineXSize},
      lineYSharpness: {type: "1f", value: initialValues.lineYSharpness},
      lineYSize: {type: "1f", value: initialValues.lineYSize},
      noiseAmplitude: {type: "1f", value: initialValues.noiseAmplitude},
      seed: {type: "1f", value: initialValues.seed},
      time: {type: "1f", value: initialValues.time},
    });
  }
  public setUniformValues(values: PartialUniformValues)
  {
    for (let key in values)
    {
      this.uniforms[key].value = values[key];
    }
  }
}

const sourceLines =
[
  "precision mediump float;",
  "",
  "#define DOMAIN 0 // 0 == pixi, 1 == shdr.bkcore.com",
  "",
  "#if DOMAIN == 0",
  "  varying vec2 vTextureCoord;",
  "  uniform sampler2D uSampler;",
  "",
  "  uniform float time;",
  "  uniform float seed;",
  "  uniform float noiseAmplitude;",
  "",
  "  uniform float aspectRatio;",
  "",
  "  uniform vec4 beamColor;",
  "  uniform float beamYPosition;",
  "",
  "  uniform float lineIntensity;",
  "  uniform float bulgeIntensity;",
  "",
  "  uniform float bulgeXPosition;",
  "  uniform vec2 bulgeSize;",
  "  uniform float bulgeSharpness;",
  "",
  "  uniform vec2 lineXSize;",
  "  uniform float lineXSharpness;",
  "",
  "  uniform float lineYSize;",
  "  uniform float lineYSharpness;",
  "",
  "",
  "#elif DOMAIN == 1",
  "  uniform vec2 resolution;",
  "  uniform float time;",
  "",
  "  const float seed = 420.69;",
  "  const float noiseAmplitude = 0.5;",
  "  float aspectRatio = resolution.x / resolution.y;",
  "",
  "  const vec4 beamColor = vec4(1.0, 0.5, 0.5, 1.0);",
  "  const float beamYPosition = 0.5;",
  "",
  "  const float bulgeXPosition = 0.4;",
  "  const vec2 bulgeSize = vec2(0.8, 0.4);",
  "  const float bulgeSharpness = 0.4;",
  "  const float bulgeIntensity = 3.0;",
  "",
  "  const vec2 lineXSize = vec2(0.4, 1.0);",
  "  const float lineXSharpness = 0.3;",
  "",
  "  const float lineYSize = 0.02;",
  "  const float lineYSharpness = 0.8;",
  "  const float lineIntensity = 5.0;",
  "",
  "",
  "#endif",
  "",
  "float hash(vec2 p)",
  "{",
  "  return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x))));",
  "}",
  "",
  "float noise(vec2 x)",
  "{",
  "  vec2 i = floor(x);",
  "  vec2 f = fract(x);",
  "  float a = hash(i);",
  "  float b = hash(i + vec2(1.0, 0.0));",
  "  float c = hash(i + vec2(0.0, 1.0));",
  "  float d = hash(i + vec2(1.0, 1.0));",
  "  vec2 u = f * f * (3.0 - 2.0 * f);",
  "  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;",
  "}",
  "",
  "float ellipseGradient(vec2 p, float ellipseXPosition, vec2 ellipseSize)",
  "{",
  "  vec2 q = vec2(-1.0 + 2.0 * p.x, p.y); // (-1, -1) -> (1, 1)",
  "  q.x -= -1.0 + 2.0 * ellipseXPosition;",
  "  q.x *= aspectRatio;",
  "  q /= ellipseSize;",
  "",
  "  float dist = length(q);",
  "",
  "  return dist;",
  "}",
  "",
  "void main()",
  "{",
  "  #if DOMAIN == 0",
  "    vec2 uv = vTextureCoord;",
  "    vec4 color = texture2D(uSampler, vTextureCoord);",
  "  #elif DOMAIN == 1",
  "    vec2 uv = gl_FragCoord.xy / resolution;",
  "    vec4 color = vec4(0.0, 0.0, 0.0, 0.0);",
  "  #endif",
  "",
  "  vec2 q = vec2(uv.x, (uv.y - beamYPosition) * 2.0);",
  "  float noiseValue = -1.0 + 2.0 * noise(vec2(q.x - time, seed));",
  "  noiseValue *= noiseAmplitude;",
  "",
  "  float yDistFromCenter = abs(q.y);",
  "  float insideLineY = step(yDistFromCenter, lineYSize);",
  "  float lineYDistanceFromEdge = distance(yDistFromCenter, lineYSize);",
  "  float lineYGradient = smoothstep(0.0, 1.0 - lineYSharpness, lineYDistanceFromEdge) * insideLineY;",
  "",
  "  float insideLineX = step(lineXSize.x, q.x) * step(q.x, lineXSize.y);",
  "  float lineXDist = 1.0 - min(distance(q.x, lineXSize.x), distance(q.x, lineXSize.y));",
  "  lineXDist = max(insideLineX, lineXDist);",
  "",
  "  float lineXGradient = smoothstep(lineXSharpness, 1.0, lineXDist);",
  "",
  "  float lineGradient = (lineYGradient * lineXGradient) * lineIntensity;",
  "  lineGradient *= 1.0 + noiseValue;",
  "",
  "  float bulgeGradient = 1.0 - ellipseGradient(q, bulgeXPosition, bulgeSize);",
  "  bulgeGradient = smoothstep(0.0, 1.0 - bulgeSharpness, bulgeGradient) * bulgeIntensity;",
  "  bulgeGradient *= 1.0 + noiseValue * 0.5;",
  "",
  "  float beamGradient = lineGradient + bulgeGradient;",
  "  color += beamGradient * beamColor;",
  "",
  "  gl_FragColor = color;",
  "}",
]
