/// <reference path="../../../lib/react-global.d.ts" />
import ListColumn from "../list/ListColumn"; // TODO refactor | autogenerated
import ListItem from "../list/ListItem"; // TODO refactor | autogenerated


import Unit from "../../Unit";
import List from "../list/List";
import {default as ItemListItem, PropTypes as ItemListItemProps} from "./ItemListItem";
import Item from "../../Item";
import AbilityBase from "../../templateinterfaces/AbilityBase";


export interface PropTypes extends React.Props<any>
{
  onDragEnd: (dropSuccesful?: boolean) => void;
  onDragStart: (item: Item) => void;
  isItemPurchaseList?: boolean;
  items: Item[];
  isDraggable: boolean;
  onRowChange: (row: ListItem<ItemListItemProps>) => void;
  
  selectedUnit?: Unit; // only used to trigger updates
}

interface StateType
{
}

export class ItemListComponent extends React.Component<PropTypes, StateType>
{
  displayName: string = "ItemList";

  getSlotIndex(slot: string)
  {
    if (slot === "high")
    {
      return 2;
    }
    else if (slot === "mid")
    {
      return 1;
    }
    else return 0;
  }

  state: StateType;

  constructor(props: PropTypes)
  {
    super(props);
    
    this.bindMethods();
  }
  private bindMethods()
  {
    this.getSlotIndex = this.getSlotIndex.bind(this);    
  }
  
  private static getAttributeProp(item: Item, attribute: string): number
  {
    if (!item.template.attributes)
    {
      return null;
    }
    else
    {
      return item.template.attributes[attribute];
    }
  }
  
  render()
  {
    var rows: ListItem<ItemListItemProps>[] = [];
    var items: Item[] = this.props.items;

    for (let i = 0; i < items.length; i++)
    {
      var item = items[i];

      var ability: AbilityBase = null;
      var abilityIsPassive = false;
      if (item.template.ability)
      {
        ability = item.template.ability;
      }
      else if (item.template.passiveSkill)
      {
        ability = item.template.passiveSkill;
        abilityIsPassive = true;
      }

      const props: ItemListItemProps =
      {
        typeName: item.template.displayName,
        slot: item.template.slot,
        unitName: item.unit ? item.unit.name : "",
        maxActionPoints: ItemListComponent.getAttributeProp(item, "maxActionPoints"),
        attack: ItemListComponent.getAttributeProp(item, "attack"),
        defence: ItemListComponent.getAttributeProp(item, "defence"),
        intelligence: ItemListComponent.getAttributeProp(item, "intelligence"),
        speed: ItemListComponent.getAttributeProp(item, "speed"),
        abilityName: ability ? ability.displayName : "",
        
        item: item,
        key: item.id,
        keyTODO: item.id,
        id: item.id,
        slotIndex: this.getSlotIndex(item.template.slot),
        unit: item.unit ? item.unit : null,
        techLevel: item.template.techLevel,
        cost: item.template.buildCost,

        ability: ability,
        abilityIsPassive: abilityIsPassive,

        isReserved: Boolean(item.unit),

        dragPositionerProps:
        {
          shouldMakeClone: true,
          forcedDragOffset: {x: 32, y: 32},
        },
        isDraggable: this.props.isDraggable,
        onDragStart: this.props.onDragStart,
        onDragEnd: this.props.onDragEnd
      };

      ["maxActionPoints", "attack", "defence",
        "intelligence", "speed"].forEach(function(stat)
      {
        if (!item.template.attributes) props[stat] = null;
        else props[stat] = item.template.attributes[stat] || null;
      });

      rows.push(
      {
        key: "" + item.id,
        content: ItemListItem(props)
      });
    }

    const columns: ListColumn<ItemListItemProps>[] =
    [
      {
        label: "Type",
        key: "typeName",
        defaultOrder: "asc"
      },
      {
        label: "Slot",
        key: "slot",
        propToSortBy: "slotIndex",
        defaultOrder: "desc"
      },
      {
        label: "Unit",
        key: "unitName",
        defaultOrder: "desc"
      },
      {
        label: "Act",
        key: "maxActionPoints",
        defaultOrder: "desc"
      },
      {
        label: "Atk",
        key: "attack",
        defaultOrder: "desc"
      },
      {
        label: "Def",
        key: "defence",
        defaultOrder: "desc"
      },
      {
        label: "Int",
        key: "intelligence",
        defaultOrder: "desc"
      },
      {
        label: "Spd",
        key: "speed",
        defaultOrder: "desc"
      },
      {
        label: "Ability",
        key: "abilityName",
        defaultOrder: "desc"
      }
    ];

   

    return(
      React.DOM.div({className: "item-list fixed-table-parent"},
        List(
        {
          listItems: rows,
          initialColumns: columns,
          initialSortOrder: [columns[1], columns[2]], // slot, unit
          onRowChange: this.props.onRowChange,
          tabIndex: 2,
          keyboardSelect: true
        })
      )
    );
  }
}

const Factory: React.Factory<PropTypes> = React.createFactory(ItemListComponent);
export default Factory;
