/// <reference path="../../../lib/react-global-0.13.3.d.ts" />
import ListItem from "./ListItem"; // TODO refactor | autogenerated

/// <reference path="itemlist.ts" />
/// <reference path="unitlist.ts" />
/// <reference path="menuunitinfo.ts" />

import Player from "../../Player";
import Unit from "../../Unit";
import MenuUnitInfo from "./MenuUnitInfo";
import UnitList from "./UnitList";
import ItemList from "./ItemList";
import Item from "../../Item";


interface PropTypes extends React.Props<any>
{
  player: Player;
}

interface StateType
{
  currentDragItem?: Item;
  selectedUnit?: Unit;
}

export class ItemEquipComponent extends React.Component<PropTypes, StateType>
{
  displayName: string = "ItemEquip";
  state: StateType;

  constructor(props: PropTypes)
  {
    super(props);
    
    this.state = this.getInitialStateTODO();
    
    this.bindMethods();
  }
  private bindMethods()
  {
    this.handleDragStart = this.handleDragStart.bind(this);
    this.handleDragEnd = this.handleDragEnd.bind(this);
    this.handleDrop = this.handleDrop.bind(this);
    this.handleSelectRow = this.handleSelectRow.bind(this);    
  }
  
  private getInitialStateTODO(): StateType
  {
    return(
    {
      selectedUnit: null,
      currentDragItem: null
    });
  }
  handleSelectRow(row: ListItem)
  {
    if (!row.data.unit) return;

    this.setState(
    {
      selectedUnit: row.data.unit
    });
  }
  handleDragStart(item: Item)
  {
    this.setState(
    {
      currentDragItem: item
    });
  }
  handleDragEnd(dropSuccesful: boolean = false)
  {
    if (!dropSuccesful && this.state.currentDragItem && this.state.selectedUnit)
    {
      var item = this.state.currentDragItem;
      if (this.state.selectedUnit.items[item.template.slot] === item)
      {
        this.state.selectedUnit.removeItem(item);
      }
    }

    this.setState(
    {
      currentDragItem: null
    });
  }
  handleDrop()
  {
    var item = this.state.currentDragItem;
    var unit = this.state.selectedUnit;
    if (unit && item)
    {
      if (unit.items[item.template.slot])
      {
        unit.removeItemAtSlot(item.template.slot);
      }
      unit.addItem(item);
    }

    this.handleDragEnd(true);
  }

  render()
  {
    var player = this.props.player;

    return(
      React.DOM.div({className: "item-equip"},
        React.DOM.div({className: "item-equip-left"},

          MenuUnitInfo(
          {
            unit: this.state.selectedUnit,
            onMouseUp: this.handleDrop,

            isDraggable: true,
            onDragStart: this.handleDragStart,
            onDragEnd: this.handleDragEnd,
            currentDragItem: this.state.currentDragItem
          }),
          ItemList(
          {
            items: player.items,
            selectedUnit: this.state.selectedUnit, // only used to trigger updates
            isDraggable: true,
            onDragStart: this.handleDragStart,
            onDragEnd: this.handleDragEnd,
            onRowChange: this.handleSelectRow
          })
        ),

        UnitList(
        {
          units: player.units,
          selectedUnit: this.state.selectedUnit,
          isDraggable: false,
          onRowChange: this.handleSelectRow,
          autoSelect: true
        })
      )
    );
  }
}

const Factory: React.Factory<PropTypes> = React.createFactory(ItemEquipComponent);
export default Factory;
