/// <reference path="../../../lib/react-0.13.3.d.ts" />
import ListColumn from "./ListColumn.d.ts"; // TODO refactor | autogenerated
import ListItem from "./ListItem.d.ts"; // TODO refactor | autogenerated
import * as React from "react";

/// <reference path="list.ts" />
/// <reference path="unitlistitem.ts" />


import Unit from "../../Unit.ts";
import List from "./List.ts";
import UnitListItem from "./UnitListItem.ts";


interface PropTypes extends React.Props<any>
{
  onMouseLeave: any; // TODO refactor | define prop type 123
  onDragStart: any; // TODO refactor | define prop type 123
  reservedUnits: any; // TODO refactor | define prop type 123
  onDragEnd: any; // TODO refactor | define prop type 123
  checkTimesActed: any; // TODO refactor | define prop type 123
  autoSelect?: any; // TODO refactor | define prop type 123
  isDraggable: boolean;
  selectedUnit: any; // TODO refactor | define prop type 123
  onMouseEnter: any; // TODO refactor | define prop type 123
  units: any; // TODO refactor | define prop type 123
  hoveredUnit: any; // TODO refactor | define prop type 123
  onRowChange: any; // TODO refactor | define prop type 123
}

interface StateType
{
}

export class UnitListComponent extends React.Component<PropTypes, StateType>
{
  displayName: string = "UnitList";
  state: StateType;

  constructor(props: PropTypes)
  {
    super(props);
  }
  
  render()
  {
    var rows: ListItem[] = [];

    for (var id in this.props.units)
    {
      var unit = this.props.units[id];

      var data: any =
      {
        unit: unit,

        id: unit.id,
        name: unit.name,
        typeName: unit.template.displayName,
        strength: "" + unit.currentHealth + " / " + unit.maxHealth,
        currentHealth: unit.currentHealth,
        maxHealth: unit.maxHealth,

        maxActionPoints: unit.attributes.maxActionPoints,
        attack: unit.attributes.attack,
        defence: unit.attributes.defence,
        intelligence: unit.attributes.intelligence,
        speed: unit.attributes.speed,

        rowConstructor: UnitListItem,
        makeClone: true,

        isReserved: (this.props.reservedUnits && this.props.reservedUnits[unit.id]),
        noActionsLeft: (this.props.checkTimesActed && !unit.canActThisTurn()),
        isSelected: (this.props.selectedUnit && this.props.selectedUnit.id === unit.id),
        isHovered: (this.props.hoveredUnit && this.props.hoveredUnit.id === unit.id),

        onMouseEnter: this.props.onMouseEnter,
        onMouseLeave: this.props.onMouseLeave,

        isDraggable: this.props.isDraggable,
        onDragStart: this.props.onDragStart,
        onDragEnd: this.props.onDragEnd
      };

      rows.push(
      {
        key: unit.id,
        data: data
      });
    }

    var columns: ListColumn[] =
    [
      {
        label: "Id",
        key: "id",
        defaultOrder: "asc"
      },
      {
        label: "Type",
        key: "typeName",
        defaultOrder: "asc"
      },
      {
        label: "Strength",
        key: "strength",
        defaultOrder: "desc",
        sortingFunction: function(a: {data: Unit;}, b: {data: Unit;})
        {
          return a.data.currentHealth - b.data.currentHealth;
        }
      },
      {
        label: "Act",
        key: "maxActionPoints",
        defaultOrder: "desc"
      },
      {
        label: "Atk",
        key: "attack",
        defaultOrder: "desc"
      },
      {
        label: "Def",
        key: "defence",
        defaultOrder: "desc"
      },
      {
        label: "Int",
        key: "intelligence",
        defaultOrder: "desc"
      },
      {
        label: "Spd",
        key: "speed",
        defaultOrder: "desc"
      }

    ];

    return(
      React.DOM.div({className: "unit-list fixed-table-parent"},
        List(
        {
          listItems: rows,
          initialColumns: columns,
          onRowChange: this.props.onRowChange,
          autoSelect: this.props.autoSelect,
          keyboardSelect: true
        })
      )
    );
  }
}

const Factory: React.Factory<PropTypes> = React.createFactory(UnitListComponent);
export default Factory;
