/// <reference path="../../../src/templateinterfaces/iculturetemplate.d.ts"/>

import app from "../../../src/App.ts"; // TODO refactor | autogenerated
export namespace Templates
{
  export namespace Cultures
  {
    export var badassCulture: CultureTemplate =
    {
      key: "badassCulture",
      nameGenerator: function(unit: Unit)
      {
        var ownCulture = app.moduleData.Templates.Cultures["badassCulture"];
        var title = getRandomProperty(ownCulture.firstNames).displayName;
        return title + " " + unit.template.displayName;
      },
      firstNames:
      {
        cool:
        {
          key: "cool",
          displayName: "Cool"
        },
        badass:
        {
          key: "badass",
          displayName: "Badass"
        }
      }
    }
  }
}
