import ArchetypeValues from "../../../src/ArchetypeValues.d.ts"; // TODO refactor | autogenerated
import Personality from "../../../src/Personality.d.ts"; // TODO refactor | autogenerated
namespace Rance
{
  export function makeRandomPersonality(): Personality
  {
    var unitCompositionPreference: ArchetypeValues = {};

    for (var archetype in app.moduleData.Templates.UnitArchetypes)
    {
      unitCompositionPreference[archetype] = Math.random();
    }

    return(
    {
      expansiveness: Math.random(),
      aggressiveness: Math.random(),
      friendliness: Math.random(),

      unitCompositionPreference: unitCompositionPreference
    });
  }
}