export const imageSources =
{
  "adelaide_hanscom1.png":                    "./assets/img/adelaide_hanscom1.png",
  "alessandro_allori1.png":                   "./assets/img/alessandro_allori1.png",
  "alessandro_allori2.png":                   "./assets/img/alessandro_allori2.png",
  "alexandre_cabanel1.png":                   "./assets/img/alexandre_cabanel1.png",
  "alexei_harlamov1.png":                     "./assets/img/alexei_harlamov1.png",
  "alexey_petrovich_antropov1.png":           "./assets/img/alexey_petrovich_antropov1.png",
  "alice_pike_barney1.png":                   "./assets/img/alice_pike_barney1.png",
  "aman_theodor1.png":                        "./assets/img/aman_theodor1.png",
  "antonello_messina1.png":                   "./assets/img/antonello_messina1.png",
  "antonio_herrera_toro1.png":                "./assets/img/antonio_herrera_toro1.png",
  "benjamin-constant1.png":                   "./assets/img/benjamin-constant1.png",
  "benoist_marie-guillemine1.png":            "./assets/img/benoist_marie-guillemine1.png",
  "bouguereau_william-adolphe1.png":          "./assets/img/bouguereau_william-adolphe1.png",
  "byron1.png":                               "./assets/img/byron1.png",
  "carl_fredric_breda1.png":                  "./assets/img/carl_fredric_breda1.png",
  "carl_fredric_breda2.png":                  "./assets/img/carl_fredric_breda2.png",
  "cramacj_lucas1.png":                       "./assets/img/cramacj_lucas1.png",
  "cranach_lucas2.png":                       "./assets/img/cranach_lucas2.png",
  "cristobal_rojas1.png":                     "./assets/img/cristobal_rojas1.png",
  "delacroix_eugene_ferdinand_victor1.png":   "./assets/img/delacroix_eugene_ferdinand_victor1.png",
  "domenikos_theotokopoulos1.png":            "./assets/img/domenikos_theotokopoulos1.png",
  "edmund_blair_leighton1.png":               "./assets/img/edmund_blair_leighton1.png",
  "edmund_blair_leighton2.png":               "./assets/img/edmund_blair_leighton2.png",
  "edwin_longsden_long1.png":                 "./assets/img/edwin_longsden_long1.png",
  "falero_luis_ricardo1.png":                 "./assets/img/falero_luis_ricardo1.png",
  "felix_bonfils1.png":                       "./assets/img/felix_bonfils1.png",
  "francesco_hayez1.png":                     "./assets/img/francesco_hayez1.png",
  "francisco_goya_lucientes1.png":            "./assets/img/francisco_goya_lucientes1.png",
  "francisco_goya_lucientes2.png":            "./assets/img/francisco_goya_lucientes2.png",
  "francisco_zurbaran1.png":                  "./assets/img/francisco_zurbaran1.png",
  "franz_von_defregger1.png":                 "./assets/img/franz_von_defregger1.png",
  "franz_von_defregger2.png":                 "./assets/img/franz_von_defregger2.png",
  "franz_von_defregger3.png":                 "./assets/img/franz_von_defregger3.png",
  "frederick_leighton1.png":                  "./assets/img/frederick_leighton1.png",
  "frederic_westin1.png":                     "./assets/img/frederic_westin1.png",
  "frederic_yates1.png":                      "./assets/img/frederic_yates1.png",
  "gaston_bussiere1.png":                     "./assets/img/gaston_bussiere1.png",
  "george_henry_hall1.png":                   "./assets/img/george_henry_hall1.png",
  "giovanni_battista_tiepolo1.png":           "./assets/img/giovanni_battista_tiepolo1.png",
  "giovanni_bellini1.png":                    "./assets/img/giovanni_bellini1.png",
  "hans_holbein1.png":                        "./assets/img/hans_holbein1.png",
  "hayez_francesco1.png":                     "./assets/img/hayez_francesco1.png",
  "henryk_siemiradzki1.png":                  "./assets/img/henryk_siemiradzki1.png",
  "ilja_jefimowitsch_repin1.png":             "./assets/img/ilja_jefimowitsch_repin1.png",
  "james_carrol_beckwith1.png":               "./assets/img/james_carrol_beckwith1.png",
  "jean-baptiste-camille_corot1.png":         "./assets/img/jean-baptiste-camille_corot1.png",
  "jean-baptiste-camille_corot2.png":         "./assets/img/jean-baptiste-camille_corot2.png",
  "jean-leon_gerome1.png":                    "./assets/img/jean-leon_gerome1.png",
  "jean-leon_gerome2.png":                    "./assets/img/jean-leon_gerome2.png",
  "jean-leon_gerome3.png":                    "./assets/img/jean-leon_gerome3.png",
  "jean-leon_gerome4.png":                    "./assets/img/jean-leon_gerome4.png",
  "john_william_godward1.png":                "./assets/img/john_william_godward1.png",
  "john_william_godward2.png":                "./assets/img/john_william_godward2.png",
  "john_william_godward3.png":                "./assets/img/john_william_godward3.png",
  "julije_klovic1.png":                       "./assets/img/julije_klovic1.png",
  "juriaen_streek1.png":                      "./assets/img/juriaen_streek1.png",
  "kiprenskij_orest_adamovic1.png":           "./assets/img/kiprenskij_orest_adamovic1.png",
  "konstantin_makovsky1.png":                 "./assets/img/konstantin_makovsky1.png",
  "lefebvre_jules_joseph1.png":               "./assets/img/lefebvre_jules_joseph1.png",
  "leon-francois_comerre1.png":               "./assets/img/leon-francois_comerre1.png",
  "leopold_loffler1.png":                     "./assets/img/leopold_loffler1.png",
  "lewis_john_frederick1.png":                "./assets/img/lewis_john_frederick1.png",
  "madrazo_garreta_raimundo1.png":            "./assets/img/madrazo_garreta_raimundo1.png",
  "marie_bashkirtseff1.png":                  "./assets/img/marie_bashkirtseff1.png",
  "moritz_kellerhoven1.png":                  "./assets/img/moritz_kellerhoven1.png",
  "nathaniel_jocelyn1.png":                   "./assets/img/nathaniel_jocelyn1.png",
  "nikolai_alexandrowitsch_jaroschenko1.png": "./assets/img/nikolai_alexandrowitsch_jaroschenko1.png",
  "nils_johan_olsson_blommer1.png":           "./assets/img/nils_johan_olsson_blommer1.png",
  "paolo_veronese1.png":                      "./assets/img/paolo_veronese1.png",
  "parmigianino1.png":                        "./assets/img/parmigianino1.png",
  "paul_cesar_helleu1.png":                   "./assets/img/paul_cesar_helleu1.png",
  "regnault_henri1.png":                      "./assets/img/regnault_henri1.png",
  "richard_bergh1.png":                       "./assets/img/richard_bergh1.png",
  "richard_bergh2.png":                       "./assets/img/richard_bergh2.png",
  "robert_dampier1.png":                      "./assets/img/robert_dampier1.png",
  "robert_lefevre1.png":                      "./assets/img/robert_lefevre1.png",
  "robert_leopold1.png":                      "./assets/img/robert_leopold1.png",
  "sichel_nathanael1.png":                    "./assets/img/sichel_nathanael1.png",
  "svetoslav_roerich1.png":                   "./assets/img/svetoslav_roerich1.png",
  "velazquez_diego1.png":                     "./assets/img/velazquez_diego1.png",
  "viktor_vasnetsov1.png":                    "./assets/img/viktor_vasnetsov1.png",
  "william-adolphe_bouguereau1.png":          "./assets/img/william-adolphe_bouguereau1.png",
};

let baseUrl = "";

export function setBaseUrl(newUrl: string): void
{
  baseUrl = newUrl;
}

export function getImageSrc(type: keyof typeof imageSources): string
{
  return new URL(imageSources[type], baseUrl).toString();
}
