/// <reference path="../../../src/templateinterfaces/iobjectivetemplate.d.ts" />

import ObjectivesAI from "../../../src/mapai/ObjectivesAI.ts"; // TODO refactor | autogenerated

import GrandStrategyAI from "../../../src/mapai/GrandStrategyAI.ts"; // TODO refactor | autogenerated

import MapEvaluator from "../../../src/mapai/MapEvaluator.ts"; // TODO refactor | autogenerated

import Player from "../../../src/Player.ts"; // TODO refactor | autogenerated

import ObjectiveTemplate from "../../../src/templateinterfaces/ObjectiveTemplate.d.ts"; // TODO refactor | autogenerated

import Objective from "../../../src/mapai/Objective.ts"; // TODO refactor | autogenerated

import Star from "../../../src/Star.ts"; // TODO refactor | autogenerated

import Unit from "../../../src/Unit.ts"; // TODO refactor | autogenerated



export var conquer: ObjectiveTemplate =
{
  key: "conquer",
  movePriority: 6,
  preferredUnitComposition:
  {
    combat: 0.65,
    defence: 0.25,
    utility: 0.1
  },
  moveRoutineFN: musterAndAttackRoutine.bind(null, buildingControllerFilter),
  unitDesireFN: defaultUnitDesireFN,
  unitFitFN: defaultUnitFitFN,
  creatorFunction: function(grandStrategyAI: GrandStrategyAI,
    mapEvaluator: MapEvaluator, objectivesAI: ObjectivesAI)
  {
    var hostilePlayers: Player[] = [];
    var diplomacyStatus = mapEvaluator.player.diplomacyStatus;
    for (var playerId in diplomacyStatus.metPlayers)
    {
      if (diplomacyStatus.statusByPlayer[playerId] >= DiplomacyState.war)
      {
        hostilePlayers.push(diplomacyStatus.metPlayers[playerId]);
      }
    }

    var relativeThreatOfPlayers = mapEvaluator.getRelativePerceivedThreatOfAllKnownPlayers();

    var possibleTargets: Star[] = [];
    for (var i = 0; i < hostilePlayers.length; i++)
    {
      var desirabilityByStar = mapEvaluator.evaluateDesirabilityOfPlayersStars(hostilePlayers[i]).byStar;
      var sortedIds = getObjectKeysSortedByValueOfProp(desirabilityByStar, "desirabilityByStar", "desc");
      if (sortedIds.length === 0)
      {
        continue;
      }
      possibleTargets.push(desirabilityByStar[sortedIds[0]].star);
    }

    var template = Modules.DefaultModule.Objectives.conquer;
    var objectives: Objective[] = [];
    for (var i = 0; i < possibleTargets.length; i++)
    {
      var star = possibleTargets[i];
      var player = star.owner;
      var threat = relativeThreatOfPlayers[player.id];
      objectives.push(new Objective(template, threat, star));
    }

    return objectives;
  },
  unitsToFillObjectiveFN: getUnitsToBeatImmediateTarget
}
