export const battle =
{
  preparing: "Preparing",
  unitIsPreparingToUseAbility: "Unit is preparing to use ability",
  guard: "Guard",
  chanceToProtect: "{guardChance}% chance to protect",
  allUnits: "all units",
  sameRowUnits: "units in same row",
  takesReducedDamage: "This unit takes {damageReduction}% reduced damage from physical attacks.",
  destroyed: "Destroyed",
  captured: "Captured",
  unitAnnihilated: "Unit annihilated",
  delay_turnOrder: "delay",
  turnsLeft: "Turns left",
  clickAnywhereToContinue: "Click anywhere to continue",

  simulateBattle: "Simulate battle",
  startBattle: "Start battle",
  autoFormation: "Auto formation",
  enemy: "Enemy",
  cantInspectEnemyFormationAsStarIsNotInDetectionRadius: "Can't inspect enemy formation as star is not in detection radius",
  own_adjective: "Own",
  attacking: "Attacking",
  defending: "Defending",
};
