export const options =
{
  options: "Options",
  resetAllOptions: "Reset all options",
  language: "Language",
  fullLanguageSupport: "Full language support",
  partialLanguageSupport: "Partial language support",
  battleAnimationTiming: "Battle animation timing",
  beforeAbility: "Before ability",
  abilityEffectDuration: "Ability effect duration",
  afterAbility: "After ability",
  unitEnter: "Unit enter",
  unitExit: "Unit exit",
  turnTransition: "Turn transition",
  debug: "Debug",
  debugMode: "Debug mode",
  AIVsAIBattleSimulationDepth: "AI vs. AI battle simulation depth",
  ui: "UI",
  alwaysExpandTopRightMenuOnLowResolution: "Always expand top right menu on low resolution",
  messageSettings: "Message settings",
  resetTutorials: "Reset tutorials",
  display: "Display",
  borderWidth: "Border width",
  areYouSureYouWantToResetAllOptions: "Are you sure you want to reset all options?",
};
