
import app from "./App"; // TODO refactor | autogenerated
import Unit from "./Unit";
import
{
  getRandomProperty
} from "./utility";

import AbilityTemplate from "./templateinterfaces/AbilityTemplate";

// TODO | add technology requirements
export default function setDynamicTemplateProperties()
{
  setAbilityGuardAddition();
  setAttitudeModifierOverride();
  setUnitFamilyAssociatedTemplates();
}
// TODO | use proper ability usage system
function setAbilityGuardAddition()
{
  function checkIfAbilityAddsGuard(ability: AbilityTemplate)
  {
    var effects = [ability.mainEffect];
    if (ability.secondaryEffects)
    {
      effects = effects.concat(ability.secondaryEffects);
    }

    var dummyUser = new Unit(getRandomProperty(app.moduleData.Templates.Units));
    var dummyTarget = new Unit(getRandomProperty(app.moduleData.Templates.Units));

    for (let i = 0; i < effects.length; i++)
    {
      effects[i].action.executeAction(dummyUser, dummyTarget, null, effects[i].data);
      if (dummyUser.battleStats.guardAmount)
      {
        return true;
      }
    }

    return false;
  }

  for (let abilityName in app.moduleData.Templates.Abilities)
  {
    var ability = <AbilityTemplate> app.moduleData.Templates.Abilities[abilityName];
    ability.addsGuard = checkIfAbilityAddsGuard(ability);
  }
}
function setAttitudeModifierOverride()
{
  for (let modifierType in app.moduleData.Templates.AttitudeModifiers)
  {
    var modifier = app.moduleData.Templates.AttitudeModifiers[modifierType];
    if (modifier.canBeOverriddenBy)
    {
      for (let i = 0; i < modifier.canBeOverriddenBy.length; i++)
      {
        if (!modifier.canBeOverriddenBy[i].canOverride)
        {
          modifier.canBeOverriddenBy[i].canOverride = [];
        }

        modifier.canBeOverriddenBy[i].canOverride.push(modifier);
      }
    }
  }
}
function setUnitFamilyAssociatedTemplates()
{
  for (let unitType in app.moduleData.Templates.Units)
  {
    var template = app.moduleData.Templates.Units[unitType];
    for (let i = 0; i < template.families.length; i++)
    {
      var family = template.families[i];
      if (!family.associatedTemplates)
      {
        family.associatedTemplates = [];
      }

      family.associatedTemplates.push(template);
    }
  }
}
